name: "Release"

# Only run when a new tag is pushed
on:
  push:
    branches:
      - '!*'
    tags:
      - '*'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends mingw-w64
          rustup target add x86_64-pc-windows-gnu x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu
          RUSTFLAGS="-C linker=x86_64-w64-mingw32-gcc" cargo build --release --target x86_64-pc-windows-gnu
          tar -czvf odbcx-x86_64-unknown-linux-gnu.tar.gz --directory target/x86_64-unknown-linux-gnu/release odbcx
          zip odbcx-x86_64-pc-windows-gnu.zip target/x86_64-pc-windows-gnu/release/odbcx.exe
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: odbcx-*


  release:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: |
              odbcx-x86_64-pc-windows-gnu.zip
              odbcx-x86_64-unknown-linux-gnu.tar.gz
